README.md, nrjavaserial/pom.xml, nrjavaserial/src/main/java/gnu/io/rfc2217/AbstractComPortCommandSwitch.java, nrjavaserial/src/main/java/gnu/io/rfc2217/BaudRateCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/ComPortCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/ComPortCommandSwitch.java, nrjavaserial/src/main/java/gnu/io/rfc2217/ComPortOptionHandler.java, nrjavaserial/src/main/java/gnu/io/rfc2217/ControlCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/DataSizeCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/FlowControlResumeCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/FlowControlSuspendCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/LineStateMaskCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/ModemStateMaskCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/NotifyLineStateCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/NotifyModemStateCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/ParityCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/PurgeDataCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/RFC2217.java, nrjavaserial/src/main/java/gnu/io/rfc2217/SignatureCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/StopSizeCommand.java, nrjavaserial/src/main/java/gnu/io/rfc2217/TelnetSerialPort.java, nrjavaserial/src/main/java/gnu/io/rfc2217/TransmitBinaryOptionHandler.java, nrjavaserial/src/main/java/gnu/io/rfc2217/Util.java, nrjavaserial/src/main/java/gnu/io/rfc2217/Version.java, nrjavaserial/src/main/java/gnu/io/rfc2217/overview.html, nrjavaserial/src/main/java/gnu/io/rfc2217/package-info.java, nrjavaserial/src/main/resources/jvser.properties
Added RFC 2217 support which enables usage of remote serial ports by incorporating the jvser library (see http://github.com/archiecobbs/jvser).
This pull request is a follow up regarding the discussion on https://github.com/crea-doo/nrjavaserial-rfc2217/issues/1.
=> RFC 2217 support

README.md, build.gradle, src/main/c/include/OSX/.gitignore
A few amalgamated cleanups in light of de06e99969c4a31498528ddc84dabc72d6c59812:
* Modify the Gradle build to only attempt archival signing when producing a build for upload. This makes it possible for the typical user to blindly run `gradle build` on a fresh checkout and get a useful result (instead of an error about not having a signatory configured).
* Update the README to reflect that the project is now built by Gradle, including build instructions.
* Don't let symlinks generated as part of the OS X built process leak into source control. Some `.gitignore` somewhere saw to it that they were eliminated from the previous source path, but it's not working now that the source has moved (or got lost in the move, or never worked and I'm misremembering things, or...).
=> Consistency cleanups

build.gradle
Uses the [Gradle OSGi plugin](https://docs.gradle.org/current/userguide/osgi_plugin.html) to accomplish what (I think) @kaikreuzer and @cbareau-Orange were trying to achieve with Maven in #29 and #31.
@madhephaestus, if this is cool with you, I'm fine with not making a release specifically for this. I'm going to try to take a look at #6/#22/#36 in the next day or so and IMHO this is the sort of thing that could be rolled into a release along with something else.
=> Add OSGi metadata to the JAR manifest

build.gradle, src/main/resources/com/neuronrobotics/nrjavaserial/build.properties
We don't want to list Apache Commons Net as an OSGi dependency as we build it into the JAR. This pull request is a follow-up to #42 and closes #29.
=> Exclude Commons packages from the OSGi imports

src/main/java/gnu/io/NativeResource.java, src/main/resources/com/neuronrobotics/nrjavaserial/build.properties
Fixes https://github.com/NeuronRobotics/nrjavaserial/issues/47.
=> Updated search order for ARM libraries.

build.gradle
It's not necessary to ship dependencies with the lib.
Changes taken from https://github.com/cvanorman/nrjavaserial/issues/1 and https://github.com/msteigenberger/nrjavaserial/commit/b9b36cbb4d83635261715188ccb945ac0ffdec72
=> Do not create a fat jar with dependencies.

build.gradle, src/main/java/gnu/io/RXTXCommDriver.java
Instead of performing a full scan of 40960 ports, on Windows it saves a
huge amount of time to get port list from the registry. In my machine
this saves MINUTES during boot phase of the library.
=> Boost startup time on Windows

src/main/java/gnu/io/NativeResource.java, src/main/java/gnu/io/RXTXCommDriver.java
Quick addition to ease the use of this library on RPi projects. This just convenience to avoid having to set the property on every launch, and has been successfully tested with the openHAB aleoncean binding.
=> Added /dev/ttyAMA to known serial ports list for RPi

src/main/c/Makefile
Without the new entries, make on Ubuntu 16.04 will complain about not finding `jni-h` and `jni_md.h`.
=> Add JNI include paths for Ununtu 16.04 Xenial

build.gradle
Try to solve an issue mentioned in https://github.com/NeuronRobotics/nrjavaserial/pull/98 where the generated MANIFEST.MF has mandatory package-imports for com.sun.jna.platform.win32and org.apache.commons.net.telnet.
Both of them should be optional.
=> Make some imports optional

build.gradle, src/main/java/gnu/io/RXTXCommDriver.java
Follow-up PR related to https://github.com/NeuronRobotics/nrjavaserial/pull/100.
Now the JNA dependency is really optional:
On Windows there is a check if the classes are present and if not available ports are detected using the old behaviour.
The RFC2217 functionality is unchanged and only needs the dependency present when a TelnetSerialPort ist instanciated (on all platforms).
=> Fix optional imports for OSGi

src/main/java/gnu/io/RXTXCommDriver.java
If this lib is used in a Windows OS environment and "com.sun.jna.platform.win32.Advapi32Util" is not present the fallback to full scan is not used.
=> registerScannedPorts not working in all cases

Makefile, README.md, src/main/c/include/SerialImp.h, src/main/c/src/SerialImp.c
I've added ggmuelle's patches to fix java 11 fixes.
Not tested for backwards compatibility yet.
=> Added Java11 Fixes by ggmuelle

src/main/java/gnu/io/RXTXPort.java
It's a bit easier to debug Java issues when the library properly names threads:
```
openhab> threads --list
Id  │ Name                                                                                           │ State         │ CPU time │ Usr time
────┼────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────┼──────────┼─────────
1   │ main                                                                                           │ WAITING       │ 372      │ 320
2   │ Reference Handler                                                                              │ WAITING       │ 11       │ 10
3   │ Finalizer                                                                                      │ WAITING       │ 16       │ 10
5   │ Signal …
```
=> Use named threads

src/main/java/gnu/io/RXTXPort.java
When a thread is closing the port it may not have obtained the `writeLock` when it is interrupted.
So it should only unlock the `writeLock` in the finally clause when the thread is holding that lock.
This fixes an `IllegalMonitorStateException` that would be thrown if the thread does not hold the lock.
An example stacktrace is:
```
java.lang.IllegalMonitorStateException: null
at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryRelease(ReentrantReadWriteLock.java:371) ~[?:1.8.0_111]
at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261) ~[?:1.8.0_111]
at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.unlock(ReentrantReadWriteLock.java:1131) ~[?:1.8.0_111]
at gnu.io.RXTXPort.close(RXTXPort.java:1101) …
```
=> Fix IllegalMonitorStateException when thread closing port is interrupted

build.gradle
This adds spotless to the gradle build. The code can be formatted with `gradle spotlessApply`. It uses the Eclipse default formatter, but VSCode integration is also available.
If this is accepted, I will file a follow-up PR to do the formatting and manually check if everything has been formatted as intended. But this should probably be done after #189 and #194 has been merged.
This has been suggested by @MrDOS https://github.com/MrDOS/nrjavaserial/pull/3#pullrequestreview-566800485 and I had it also in my mind.
=> Add formatter

.gitattributes, .github/workflows/build.yml, build.gradle
This way, old errors don't break the build.
=> Enable Spotless' ratchetting mode

README.md, build.gradle, src/main/c/Makefile, src/main/c/include/SerialImp.h, src/main/c/include/slf4j.h, src/main/c/src/SerialImp.c, src/main/c/src/slf4j.c, src/main/c/src/windows/termios.c, src/main/java/gnu/io/CommPort.java, src/main/java/gnu/io/CommPortEnumerator.java, src/main/java/gnu/io/CommPortIdentifier.java, src/main/java/gnu/io/NRSerialPort.java, src/main/java/gnu/io/NativeResource.java, src/main/java/gnu/io/RXTXCommDriver.java, src/main/java/gnu/io/RXTXPort.java, src/main/java/gnu/io/Zystem.java, src/main/java/gnu/io/factory/SerialPortRegistry.java, src/main/java/gnu/io/rfc2217/ComPortOptionHandler.java, src/main/java/gnu/io/rfc2217/TelnetSerialPort.java, test/src/test/NRJavaSerialTest.java, test/src/test/ReadTest.java
This is a prototype of the functionality suggested in #193. It seems to work well enough. At the beginning of every JNI function, I call a setup macro which pushes a reference to the `JNIEnv` and `jobj` or `jclass` onto a thread-local stack; then I replace the `report_error`/`report_warning`/`report`/`report_verbose` functions with one which retrieves the current JNI context from that stack and uses it to look up and call the appropriate SLF4J logging function.
The result is _very_ noisy. At the default `DEBUG` level of filtering, both Java and native code spam a lot of messages about their internal processes. If you enable `TRACE`-level output, you get a lot of extremely fine-level detail, mostly from `report_verbose()` in the native code. Stuff that no one would care about – like …
=> Use SLF4J for logging

build.gradle
I really want to start to use Spotless, and having it run automatically on `gradle check` is part of its magic – but it needs to not cause build failures due to formatting errors in areas which haven't changed. I was hoping ratchetting mode would be sufficient, but that still checks formatting on a whole-file basis. E.g., if a file `Foo.java` was changed, then the _entire_ `Foo.java` is checked for formatting errors, not just the area of the diff. In a project like this where the majority of the source is (currently, lamentably) kept in a couple multi-thousand-line files, you can't sensibly apply formatting fixes on a file-by-file basis along with other changes. It masks the real diff too much. I'm about to open a PR to fix #197; it's +259 -103. But because it touches `RXTXPort.java`, it …
=> Disable Spotless on `gradle check` for now

src/main/c/src/SerialImp.c
`mkstemp(3)` creates and opens a file descriptor for a temporary file, but this file descriptor was immediately discarded in favour of
`fopen(3)`'ing the file by name and using that `FILE *` stream. I'm sure whoever originally wrote this code meant to use `mktemp(3)` instead, which only creates a unique file from a template name (equivalent to `mktemp(1)`).
This fixes https://github.com/openhab/openhab-core/issues/1842 and mitigates #111.
=> Fix FD leak when checking lock dir permissions

src/main/c/Makefile
The build fails if the JDK is located in a path with spaces.
=> Fix build if JAVA_HOME contains spaces

src/main/c/include/SerialImp.h, src/main/c/src/SerialImp.c
- increase buffer sizes
- change sprintf() calls to snprintf() calls introducing respective
maximum size arguments
- remove #if / #endif blocks dealing with system names on Linux
- comment message informing the user that locking worked
- correct variable name and remove unused buffer name[80] in uucp_lock()
It would be great if someone could test this because I'm not a C(++) developer and don't have the toolchains installed.
=> [issue #229] Prevent Buffer Overflows When Constructing Messages

README.md
This makes it easier to find the latest build results when the badge indicates that the build failed.
=> Link build badge to workflow builds

build.gradle
This newer version addresses CVE-2021-37533 which prevents issues for users who use this older version as a transitive nrjavaserial dependency.
For release notes, see:
https://commons.apache.org/proper/commons-net/changes-report.html
Fixes #237
=> Upgrade commons-net to 3.9.0 to address CVE-2021-37533
